#!/bin/sh


VERSION="1.6"
DEST="/tmp/._bdlstub_bigdl.bin"

ARCH="$(uname -m)"
if [ "$ARCH" = "x86_64" ]; then
    ARCH_SUFFIX="amd64"
elif [ "$ARCH" = "aarch64" ]; then
    ARCH_SUFFIX="arm64"
else
    echo "Unsupported architecture: $ARCH"
    exit 1
fi

BIGDL="https://github.com/xplshn/bigdl/releases/download/$VERSION/bigdl_${ARCH_SUFFIX}"

if [ "$1" = "--install" ]; then
    DEST="$2"
fi

if [ -f "$DEST" ]; then
    "$DEST" "$@"
else
    mkdir -p "$(dirname "$DEST")"
    if command -v wget >/dev/null 2>&1; then
        wget -q "$BIGDL" -O "$DEST"
    elif command -v curl >/dev/null 2>&1; then
        curl -qfsSL "$BIGDL" -o "$DEST"
    else
        echo "Neither wget nor curl is available."
        exit 1
    fi
    chmod +x "$DEST"
    [ "$1" = "--install" ] || "$DEST" "$@"
fi
